"""
Training script for EEG-NeXt on Mind Wandering detection
Uses CWT scalograms from preprocessed EEG data
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report, confusion_matrix
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from tqdm import tqdm
import json

from eegnext_model import create_eegnext


class EEGScalogramDataset(Dataset):
    """
    Dataset for EEG scalograms

    Loads CWT data generated by cwt_convolution.py
    """

    def __init__(self, cwt_data_path, use_power=True, normalize=True):
        """
        Args:
            cwt_data_path: Path to NPZ file with CWT data
            use_power: Use power instead of complex data
            normalize: Normalize scalograms
        """
        # Load data
        data = np.load(cwt_data_path)

        if use_power:
            self.scalograms = data['power']  # (n_epochs, n_channels, n_freq, n_times)
        else:
            # Use magnitude of complex data
            self.scalograms = np.abs(data['data']) ** 2

        self.labels = data['label']
        self.frex = data['frex']
        self.times = data['times']
        self.ch_names = data['ch_names']

        # Normalize if requested
        if normalize:
            self._normalize()

        print(f"Loaded dataset:")
        print(f"  Scalograms shape: {self.scalograms.shape}")
        print(f"  Labels: {np.bincount(self.labels)}")
        print(f"  Frequency range: {self.frex[0]:.1f} - {self.frex[-1]:.1f} Hz")
        print(f"  Time range: {self.times[0]:.1f} - {self.times[-1]:.1f} s")

    def _normalize(self):
        """
        Normalize scalograms

        Strategy: Z-score normalization per channel
        """
        n_epochs, n_channels, n_freq, n_times = self.scalograms.shape

        for ch in range(n_channels):
            # Compute mean and std across all epochs for this channel
            ch_data = self.scalograms[:, ch, :, :]
            mean = ch_data.mean()
            std = ch_data.std()

            # Normalize
            self.scalograms[:, ch, :, :] = (ch_data - mean) / (std + 1e-8)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        scalogram = torch.FloatTensor(self.scalograms[idx])
        label = torch.LongTensor([self.labels[idx]])[0]
        return scalogram, label


def train_epoch(model, dataloader, criterion, optimizer, device):
    """Train for one epoch"""
    model.train()
    running_loss = 0.0
    all_preds = []
    all_labels = []

    pbar = tqdm(dataloader, desc='Training')
    for scalograms, labels in pbar:
        scalograms = scalograms.to(device)
        labels = labels.to(device)

        # Forward
        optimizer.zero_grad()
        outputs = model(scalograms)
        loss = criterion(outputs, labels)

        # Backward
        loss.backward()
        optimizer.step()

        # Statistics
        running_loss += loss.item()
        preds = torch.argmax(outputs, dim=1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

        # Update progress bar
        pbar.set_postfix({'loss': loss.item()})

    epoch_loss = running_loss / len(dataloader)
    epoch_acc = accuracy_score(all_labels, all_preds)

    return epoch_loss, epoch_acc


def validate_epoch(model, dataloader, criterion, device):
    """Validate for one epoch"""
    model.eval()
    running_loss = 0.0
    all_preds = []
    all_probs = []
    all_labels = []

    with torch.no_grad():
        pbar = tqdm(dataloader, desc='Validation')
        for scalograms, labels in pbar:
            scalograms = scalograms.to(device)
            labels = labels.to(device)

            # Forward
            outputs = model(scalograms)
            loss = criterion(outputs, labels)

            # Get predictions and probabilities
            probs = torch.softmax(outputs, dim=1)
            preds = torch.argmax(outputs, dim=1)

            # Statistics
            running_loss += loss.item()
            all_preds.extend(preds.cpu().numpy())
            all_probs.extend(probs[:, 1].cpu().numpy())  # Prob of class 1 (MW)
            all_labels.extend(labels.cpu().numpy())

            pbar.set_postfix({'loss': loss.item()})

    epoch_loss = running_loss / len(dataloader)
    epoch_acc = accuracy_score(all_labels, all_preds)
    epoch_auc = roc_auc_score(all_labels, all_probs)

    return epoch_loss, epoch_acc, epoch_auc, all_preds, all_labels


def train_model(model, train_loader, val_loader, num_epochs, device, save_path):
    """
    Complete training loop
    """
    # Loss function with class weights (if imbalanced)
    criterion = nn.CrossEntropyLoss()

    # Optimizer (AdamW as in paper)
    optimizer = optim.AdamW(
        model.parameters(),
        lr=1e-4,  # Constant learning rate (paper)
        weight_decay=5e-4,  # Weight decay (paper)
        betas=(0.9, 0.999),
        eps=1e-8
    )

    # Training history
    history = {
        'train_loss': [],
        'train_acc': [],
        'val_loss': [],
        'val_acc': [],
        'val_auc': []
    }

    best_val_auc = 0.0
    best_epoch = 0

    for epoch in range(num_epochs):
        print(f"\nEpoch {epoch + 1}/{num_epochs}")
        print("-" * 50)

        # Train
        train_loss, train_acc = train_epoch(
            model, train_loader, criterion, optimizer, device
        )

        # Validate
        val_loss, val_acc, val_auc, val_preds, val_labels = validate_epoch(
            model, val_loader, criterion, device
        )

        # Update history
        history['train_loss'].append(train_loss)
        history['train_acc'].append(train_acc)
        history['val_loss'].append(val_loss)
        history['val_acc'].append(val_acc)
        history['val_auc'].append(val_auc)

        # Print stats
        print(f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.4f}")
        print(f"Val Loss: {val_loss:.4f} | Val Acc: {val_acc:.4f} | Val AUC: {val_auc:.4f}")

        # Save best model
        if val_auc > best_val_auc:
            best_val_auc = val_auc
            best_epoch = epoch
            torch.save({
                'epoch': epoch,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'val_auc': val_auc,
                'val_acc': val_acc,
            }, save_path / 'best_model.pth')
            print(f"✓ Best model saved (AUC: {val_auc:.4f})")

    print(f"\nTraining complete!")
    print(f"Best epoch: {best_epoch + 1} with Val AUC: {best_val_auc:.4f}")

    return history


def cross_validation_training(cwt_data_path, output_dir, n_folds=5, num_epochs=10):
    """
    5-fold cross-validation training (as in paper)
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(exist_ok=True, parents=True)

    # Load dataset
    dataset = EEGScalogramDataset(cwt_data_path, use_power=True, normalize=True)

    # Get all labels for stratification
    all_labels = dataset.labels

    # Setup device
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"\nUsing device: {device}")

    # Cross-validation
    skf = StratifiedKFold(n_splits=n_folds, shuffle=True, random_state=42)

    fold_results = []

    for fold, (train_idx, val_idx) in enumerate(skf.split(np.zeros(len(all_labels)), all_labels)):
        print("\n" + "=" * 70)
        print(f"FOLD {fold + 1}/{n_folds}")
        print("=" * 70)

        # Create fold directory
        fold_dir = output_dir / f'fold_{fold + 1}'
        fold_dir.mkdir(exist_ok=True)

        # Create data samplers
        train_dataset = torch.utils.data.Subset(dataset, train_idx)
        val_dataset = torch.utils.data.Subset(dataset, val_idx)

        # Create dataloaders (batch size 128 as in paper)
        train_loader = DataLoader(
            train_dataset,
            batch_size=128,  # As in paper
            shuffle=True,
            num_workers=4,
            pin_memory=True
        )

        val_loader = DataLoader(
            val_dataset,
            batch_size=128,
            shuffle=False,
            num_workers=4,
            pin_memory=True
        )

        print(f"Train samples: {len(train_dataset)}")
        print(f"Val samples: {len(val_dataset)}")

        # Create model
        model = create_eegnext(
            in_channels=dataset.scalograms.shape[1],  # Number of channels
            num_scales=dataset.scalograms.shape[2],  # Number of frequencies
            num_times=dataset.scalograms.shape[3],  # Number of time points
            num_classes=2,
            pretrained=True
        ).to(device)

        # Train
        history = train_model(
            model, train_loader, val_loader,
            num_epochs, device, fold_dir
        )

        # Load best model for final evaluation
        checkpoint = torch.load(fold_dir / 'best_model.pth')
        model.load_state_dict(checkpoint['model_state_dict'])

        # Final evaluation
        _, val_acc, val_auc, val_preds, val_labels = validate_epoch(
            model, val_loader, nn.CrossEntropyLoss(), device
        )

        # Save results
        fold_results.append({
            'fold': fold + 1,
            'val_acc': val_acc,
            'val_auc': val_auc,
            'best_epoch': checkpoint['epoch']
        })

        # Save confusion matrix
        cm = confusion_matrix(val_labels, val_preds)
        plt.figure(figsize=(8, 6))
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
        plt.title(f'Confusion Matrix - Fold {fold + 1}')
        plt.ylabel('True Label')
        plt.xlabel('Predicted Label')
        plt.savefig(fold_dir / 'confusion_matrix.png', dpi=150, bbox_inches='tight')
        plt.close()

        # Save classification report
        report = classification_report(val_labels, val_preds,
                                       target_names=['On-Task', 'Mind Wandering'])
        with open(fold_dir / 'classification_report.txt', 'w') as f:
            f.write(report)

        # Save history
        with open(fold_dir / 'history.json', 'w') as f:
            json.dump(history, f, indent=2)

        print(f"\nFold {fold + 1} Results:")
        print(f"  Accuracy: {val_acc:.4f}")
        print(f"  AUC: {val_auc:.4f}")

    # Aggregate results
    print("\n" + "=" * 70)
    print("CROSS-VALIDATION RESULTS")
    print("=" * 70)

    accs = [r['val_acc'] for r in fold_results]
    aucs = [r['val_auc'] for r in fold_results]

    print(f"\nAccuracy: {np.mean(accs):.4f} ± {np.std(accs):.4f}")
    print(f"AUC: {np.mean(aucs):.4f} ± {np.std(aucs):.4f}")

    print("\nPer-fold results:")
    for r in fold_results:
        print(f"  Fold {r['fold']}: Acc={r['val_acc']:.4f}, AUC={r['val_auc']:.4f}")

    # Save aggregate results
    with open(output_dir / 'cv_results.json', 'w') as f:
        json.dump({
            'fold_results': fold_results,
            'mean_acc': float(np.mean(accs)),
            'std_acc': float(np.std(accs)),
            'mean_auc': float(np.mean(aucs)),
            'std_auc': float(np.std(aucs))
        }, f, indent=2)

    return fold_results


if __name__ == "__main__":
    """
    Run training
    """
    # Paths
    cwt_data_path = 'preprocessing/session_1/001_01_cwt_data.npz'
    output_dir = 'models/eegnext'

    # Run cross-validation
    results = cross_validation_training(
        cwt_data_path=cwt_data_path,
        output_dir=output_dir,
        n_folds=5,
        num_epochs=10  # Paper uses 10 epochs
    )

    print("\n✓ Training complete!")